{% set name = 'efmtool_link' %}
{% set version = '0.0.8' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cnapy-org/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1caba9e89ff275455e5abe4197b113586a7da2bb2cd94ac1410a9463de445b62

build:
  noarch: python
  number: 0  # NOTE: increment for new build/set to zero for new version
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.7,<3.11
    - jpype1
    - openjdk
    - install-jdk
  run:
    - python >=3.7,<3.11
    - numpy
    - jpype1
    - cobra >=0.26.3
    - psutil
    - scipy
    - openjdk

test:
  imports:
    - efmtool_link
  requires:
    - pip
  commands:
    - pip check

about:
  home:  https://github.com/cnapy-org/efmtool_link
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: Framework for calling selected functions of efmtool
  doc_url: https://github.com/cnapy-org/efmtool_link
  dev_url: https://github.com/cnapy-org/efmtool_link

extra:
  recipe-maintainers:
    - axelvonkamp
